### PR TITLE
Fix #826 / Use async-std instead of futures

### LINKED ISSUE #826: "Cannot execute LocalPool executor from within another executor" `panic!` on `master`
A user on matrix mentioned they're running into the following `panic!` on Windows 10:

```
thread 'main' panicked at 'cannot execute LocalPool executor from within another executor: EnterError'.
```

Another user confirmed, and mentioned that the recently released `0.18.1` works, so the issue must be in one of the recent unreleased changes. Seeing as we're getting an executor error, I imagine this must be related to either the new `async` run code or the `wgpu` async code, or maybe the interaction between the two (which I think we always immediately block on anyway). cc @Woyten any ideas on what might be going on? I'll see if I can get some more detailed backtraces, etc.

### PR DESCRIPTION
**Pull request by Woyten**
This PR fixes #826 without reverting the `async` functions.

Since I didn't manage to make the code run using the `futures` library I tried using `async-std` instead which I perceive as a very solid `async` replacement for `std`.

One problem remains: Nannou is not terminating properly. It might have something to do with daemon threads now being non-daemon threads.

### CODE REVIEW

File: nannou/src/window.rs [hunk 1]
```diff
@@ -726,9 +726,10 @@ impl<'app> Builder<'app> {
         self
     }
 
+    #[cfg(not(target_os = "unknown"))]
```
Comment (Woyten) [inline nannou/src/window.rs:729]: To understand this it's worth checking the implementation of `async_std::task_block_on`. The return type depends on whether your `target_os` is `"unknown"` or not.

File: nannou/src/window.rs [hunk 2]
```diff
@@ -726,9 +726,10 @@ impl<'app> Builder<'app> {
...
     /// Builds the window, inserts it into the `App`'s display map and returns the unique ID.
     pub fn build(self) -> Result<Id, BuildError> {
-        futures::executor::block_on(self.build_async())
+        async_std::task::block_on(self.build_async())
     }
 
     pub async fn build_async(self) -> Result<Id, BuildError> {
```
Comment (Woyten) [inline nannou/src/window.rs:735]: We could think about putting `#[cfg(target_os = "unknown")]` or `#[cfg(feature = "wasm-experimental")]` here s.t. the `async` we are flexible to change the `async` concept without introducing breaking changes to "normal" users i.e. those that do not use `wasm-experimental`.

File: nannou_wgpu/src/texture/capturer.rs [hunk 3]
```diff
@@ -61,49 +53,10 @@ struct ConverterDataPair {
 pub struct Rgba8AsyncMappedImageBuffer<'buffer>(wgpu::ImageReadMapping<'buffer>);
 
 impl ThreadPool {
-    /// Spawns the given future if a worker is available. Otherwise, blocks and waits for a worker
-    /// to become available before spawning the future.
-    fn spawn_when_worker_available<F>(&self, future: F) -> Result<(), AwaitWorkerTimeout<F>>
```
Comment (Woyten) [inline nannou_wgpu/src/texture/capturer.rs:66]: I have no idea whether this code is important or not. It looks to me as if something is done manually that should be handled by a thread pool executor.

Comment (Woyten) [reply nannou_wgpu/src/texture/capturer.rs:66]: Okay... I see this breaks more things...

**Comment by Woyten** [comment]
> One problem remains: Nannou is not terminating properly. It might have something to do with daemon threads now being non-daemon threads.

@mitchmindtree I can no longer reproduce the problem. Maybe someone else could check if the change works for them?

**Comment by mitchmindtree** [comment]
Nice one @Woyten!

I've tested this locally (linux native) and it seems to work nicely, that includes the app and capture examples :+1: 

> async-std

It would be nice if nannou could avoid picking between a particular async runtime (e.g. tokio, async-std, smol), or at least allow for a user to specify their own (while providing an easy default for users who don't care). That said, until we can write async methods for traits, I don't think there's a practical way of achieving this for nannou without some serious refactoring, and I think you're right in that `async-std` is a pretty solid standard to settle on in the meantime.

> One problem remains: Nannou is not terminating properly

Ah I think you might be running into an unrelated issue https://github.com/nannou-org/nannou/issues/728.

@Woyten would you mind sharing which platform you tested this on? I'm with @JoshuaBatty, we might just test with windows and macos before landing.

**Comment by melMass** [comment]
Hello,

Following a chain of issues I ended up here.
I've just tested all wgpu examples (currently trying all others to see), and they now work well on macOS!

@mitchmindtree feel free to ask me stuffs to test on macOS if needed

Thanks

**Comment by Woyten** [comment]
@mitchmindtree Thanks for checking!

> It would be nice if nannou could avoid picking between a particular async runtime

I am not an expert but I think once you use functions like `spawn(_local)` you will always have to pick an async runtime. For example when using `async-std` you implicitly pick the `async_global_executor` runtime. However, since `spawn(_local)` is only used in `capturer.rs` and the used runtime is invisible to the Nannou user I do not know if this really matters much.

> Ah I think you might be running into an unrelated issue #728.

Yes, seems to be it. Phew! :smiley: 

> @Woyten would you mind sharing which platform you tested this on? I'm with @JoshuaBatty, we might just test with windows and macos before landing.

Unfortunately I cannot deliver any new datapoint since I am using Linux as well. But @melMass tested in on macOS. Thank you!

**Comment by JoshuaBatty** [comment]
I just tested on Mac OS and it all seems to be running fine.

Also tested on Windows. Everything compiles and runs fine except the `draw_capture` example seems to be running 4x quicker than the `draw` example. I do have my monitor's refresh rate set to 240Hz just FYI. Running `draw` seems to be updating at normal speed however.

**Comment by mitchmindtree** [comment]
Nice, time to land it!

>  4x quicker than the draw example. I do have my monitor's refresh rate set to 240Hz

It looks like this is just because `draw_capture` uses a fixed time-step interval (`frame.nth() / 60.0`).
